services:
  pg-db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=imigz 
      - POSTGRES_USER=admin
    ports:
      - 5432:5432
    volumes:
      - pgData:/var/lib/postgresql

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_PERSISTENCE=1
      - HOSTNAME_EXTERNAL=localhost

    volumes:
      - './localstack-init.sh:/etc/localstack/init/ready.d/init-aws.sh'
      # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # app: 
  #   build: .
  #   ports:
  #     - 3000:3000

volumes:
  pgData: