name: CD

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed
    branches:
      - 'main'
    
  
jobs:
  public:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
    - run: docker ps
  