name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  node-version: 19.x
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build
    - name: Saving dist artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
        
  lint:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ env.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ env.node-version }}
            cache: 'npm'
        - run: npm install
        - run: npm run lint
        
  test:
      needs: [build, lint]
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ env.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ env.node-version }}
            cache: 'npm'
        - name: Download a dist artifact
          uses: actions/download-artifact@v3
          with:
            name: dist
            path: dist

        - run: sudo chmod u+x localstack-init.sh
        - run: docker-compose up -d
        - run: sleep 1m
        - run: npm install
        - run: npm run migrate:latest
        - run: npm run test

